/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.socialworld.java-application-conventions")
}

dependencies {
    // https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client
    implementation("org.mariadb.jdbc:mariadb-java-client:3.1.4")
}

application {
    // Define the main class for the application.
    mainClass.set("org.socialworld.SocialWorld")
}
